# Generated by Django 3.0.8 on 2020-08-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sss_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmessage',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
